### ISSUE TITLE
Exception has been thrown by the target

### ISSUE THREAD

**Issue by Gama101** [Funbit/ets2-telemetry-server#1]
Hi. After running telemetry server as admin, there appears error message which says "Exception has been thrown by the target". After that, server say that its running, but there are IP not connected with my local area network, and i cant access it. If i run it without admin mode, it provide good ip address, but i cant access it from my smartphone.

Here are some screens

Running with admin rights
![bad_ip](https://cloud.githubusercontent.com/assets/1129947/5577944/de6b78d2-901c-11e4-82a0-829918a23de7.png)
Running without admin rights
![good_ip_not_as_admin](https://cloud.githubusercontent.com/assets/1129947/5577945/de71771e-901c-11e4-9830-4743a4403be1.png)

Im using Windows 8.1 x64 and i have steam version of the game. Plugin was putted as it is described in tutorial. Running in compatibility mode with Windows 7 does nothing.

Thanks for any respone!

**Comment by Funbit** [comment]
I have merged proposed commits. You may download the updated version here:
https://github.com/Funbit/ets2-telemetry-server

Thank you again for your feedback!
