### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by jack-douglas** [Funbit/ets2-telemetry-server#110]
What is the default currency that the game is using for this [https://gyazo.com/668efecf96ee1358280b9f8ff60b78ee](url)

**Comment by mike-koch** [comment]
EUR for ETS2 and USD for ATS. If you need currency conversion factors, I believe this chart is up-to-date: https://github.com/mike-koch/ets2-mobile-route-advisor/wiki/Side-Notes#currency-code-multipliers

**Comment by jack-douglas** [comment]
Well i am making a live tracking system for a vtc. i have done a delivery and the total money was £9686 but the software sends 7749
