### ISSUE TITLE
Check gears for modded trucks

### ISSUE THREAD

**Issue by Funbit** [Funbit/ets2-telemetry-server#13]
By the way, trucks with modded gearboxes (18 gears for example) show gears wrong, i don't know if it is something on scs's side or on your side.

**Comment by thorerik** [comment]
Wrong repo? I guess this is belonging to nlhans/ets2-sdk-plugin

**Comment by Funbit** [comment]
I should first check if it is related to my server. If not then I'll post it in ets2-sdk-plugin.
