### ISSUE TITLE
Logitech G13 Question

### ISSUE THREAD

**Issue by Woody033** [Funbit/ets2-telemetry-server#145]
I have a Logitech G13 and what I am looking/hopping to do is use the the onboard programing to simplify some hot keys. 

For example, Cruise Control...
The onboard programing is in LUA. Would it be possible to check the CC  status?
I have done some LUA programing in the past, but not something like this any guidance would be appreciated. 
Cordially,
Wøødy

**Comment by KS-HTK** [comment]
Hey, what exactly do you hope to achieve with the G13? If you want to be able to control the CC that should be possible without LUA, if you want to display the information on the display of the G13 I would look into if the G13 can show information from a web endpoint.

I do not have a G13 or G19 so I do not know the capabilities of the lcd. But for my G110 I have the G keys mapped to F13 to F24 (normal keyboard keys nearly no keyboard has) so I am able to use them in nearly every software as hotkeys without even needing to touch the Logitech software. 

For the G keys there is a [SDK](https://www.logitechg.com/de-de/innovation/developer-lab.html) on logitechg.com but I dont know about the lcd.

**Comment by Woody033** [comment]
Hello KS-HTK,
What I was trying to achieve was for example, the CC, was on, that the button pressed would do one action, and if the CC was off, the button would do another action. 
In order to do that, the controller would have to be able to retrieve the telemetry from the game.
Some wheels can receive RPM for example, it was just an extension of that.
I had not though of looking at the SDK, Thank You!
Cordially,
Wøødy

**Comment by KS-HTK** [comment]
So I did a bit more reading about this. It seems to not work. Logitech has sivirly limited the capabilities of the LUA engine in LGS. Installing Packages is not possible and I could not find a way to get web endpoints without a package. There seems to be a possibility to escape the LGS LUA sandbox, but I have not read into that.

Also `file` `io`, `package` and `system` are not available from within LGS so exporting it to a file and reading that is not a option.

**Comment by Woody033** [comment]
Thank for looking further into it.
