### ISSUE TITLE
Telemetry SDK issues

### ISSUE THREAD

**Issue by Funbit** [Funbit/ets2-telemetry-server#16]
1) job information is not properly updated after job completion or after switching the profile (telemetry continues to report old information)

2) it seems not possible to determine whether the trailer is attached right now or not (i.e. when you attach/detach it using T key). Would be great if they can fix this issue.

3) currently, the gear reported by the telemetry sdk reflects the PHYSICAL gear, but it would be nice to have LOGICAL gear value which is what is shown on the in-game dashboard (the details of this limitation were explaned here http://forum.scssoft...171000&start=10 )

**Comment by Marko1996** [comment]
please fix  job information is not properly updated after job completion or after switching the profile (telemetry continues to report old information)

**Comment by Funbit** [comment]
The stuff mentioned in this topic is not related to my project. It is an SDK limitation for now.

**Comment by Marko1996** [comment]
i have a problem whn i speed up on mobile dashboard display it says 30.9595959,can you help me how to fix this

**Comment by yodek** [comment]
You can add in skin folder to file dashboard.js this:
data.truckSpeed = Math,floor(data.truckSpeed);

**Comment by Funbit** [comment]
I have moved the speed issue here
https://github.com/Funbit/ets2-telemetry-server/issues/40

**Comment by Marko1996** [comment]
can you give me a link of v2.1.0 or v2.0.0
Dana 2. 3. 2015. 13:41 "Funbit" <notifications@github.com> je napisao/la:

**Comment by nlhans** [comment]
1) I am unaware if SCS provides an event to clear the job info. I could take a look.
Personally I have always use trailer attached as a mask to show active job or hide it.

2) The trailer attached flag readout is a boolean that had some issues reading out properly with C# (especially demo code of a while back). I haven't experienced any problems with the new implementation.

3) I normally do not play or test with automatic gear shifter of SCS. Moreover the gear info is just the straight value reported from the SCS SDK. So I am not sure if there is anything I can do about that.

**Comment by Funbit** [comment]
@nlhans : 
1) Most probably telemetry SDK does not have such event :( Hope it will be added later.
2) I'm sure that trailer attached flag is read correctly, but it is not changed when trailer gets attached/detached when T key is pressed (would be great if it does, don't know if it is possible to implement using current version of the telemetry SDK)
3) Yea, it is not a problem of your plugin, it is just a request for another property to be available via telemetry SDK. Hope it will be added later.

Thanks for the support.

**Comment by iliketrainz98** [comment]
HI There,

We are developing another application and we found that nlhans code did update when trailer was attached/unattached whereas funbit's code did not. We are looking into why at the moment, but some ideas would be great.

We are also currently using the trailer attached/detached to figure out if on job or not (funbits code for job on/off doesn't work). Any ideas of how we can achieve this?

Thanks!
Tom

**Comment by Funbit** [comment]
@iliketrainz98 
Thank you for the point. It was my fault, I forgot to remove the workaround after trailerAttached was fixed. Now hasJob and trailerAttached properties share the same value, so pressing T button in game instantly removes/shows trailer in the mobile dashboard.

So there is only one issue left (the (1) one, because (3) is not an actual issue) to solve.

**Comment by Funbit** [comment]
All issues have been fixed in 3.0.0.
