### ISSUE TITLE
Implement telemetry broadcasting to external URL

### ISSUE THREAD

**Issue by Funbit** [Funbit/ets2-telemetry-server#18]

**Comment by Funbit** [comment]
Implemented in 2.0.0.

**Comment by fstingl** [comment]
Hey, is there a documentation for broadcast post request namings?

**Comment by dreadrecords** [comment]
For a free Steam gift go to http://getsteamgifts.com/ I got my Steam Gift Card there!

**Comment by yodek** [comment]
Where is report button ? Just to ban @dreadrecords for spam [ btw. I checked website in past - CRAP SHIT ].

**Comment by Funbit** [comment]
@fstingl 
Hi, glad that you found the solution, but just in case I'll post it here:

To enable telemetry broadcasting one just need to open Ets2Telemetry.exe.config file and set the BroadcastUrl parameter, like this:

<add key="BroadcastUrl" value="http://myserver.com/optional/path/to/script" />

The server will be sending POST HTTP requests to that URL with telemetry JSON (as you see it in http://localhost:25555/api/ets2/telemetry ) as body. So to get the telemetry data on the other side you just have to read HTTP request content as a string and deserialize JSON to an object.

By default broadcasting is done every 10 seconds. You may change the time by editing BroadcastRate parameter.

**Comment by dreadrecords** [comment]
yodek commented Mar 29, 2015 
YODEK i want to mail yu but unable
Don't need to ban or acuse if yu dont know about it  or at least ask first.
Cause there's a problem with my facebook acount and someone is posting in other places and steam also  using my name i'm trying to fix and already take care of it
Not even had time to see the post here
So before yu coment or judge  someone ask or send a message.
i'm no kid i'm 46years old and i dont play with other people work or stuff Tanks
Carlos
