### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by lexik223** [Funbit/ets2-telemetry-server#26]
Hi, i have got small problem with instalation on windows Xp... My friend downloaded this aplication for this OS too, but he haven't got problem... But when i want install Ets2telemetry.exe soo that will answer to me that Ets2telemtry.exe isn't valid aplication for 32 bit system... Can you help me?

**Comment by thorerik** [comment]
Do you have .net 4.0 installed?
You can get it from here if you don't:
http://www.microsoft.com/en-us/download/details.aspx?id=17718

On that note, you should consider upgrading way from XP as it is no longer
supported.

-- 
Thor Lie

**Comment by Funbit** [comment]
Windows XP is not supported, and will not be because it does not support .NET Framework 4.5+.
 Please consider upgrading to Windows 7 and later.
