### ISSUE TITLE
create a copy of the default skin with MPH

### ISSUE THREAD

**Issue by Funbit** [Funbit/ets2-telemetry-server#34]

**Comment by imaggot** [comment]
![dashboard](https://cloud.githubusercontent.com/assets/11467092/6647989/45156c58-c9cc-11e4-9145-b15b84e20f13.jpg)
hi, i made one for myself, i just saw this msg so i emailed the file to funbit@gmail.com, also where it displays the actual speed in the little box it still shows kph, but when in uk and you see mph speed sign you can match it to the mph on the default skin with the mph that i added, it made it whole lot easier i found..... in the meantime i hope this helps people till somebody makes a better one :), im not sure if itll be put on here or if it will be how long it will take, so anybody who wants it please feel free to email me with subject as "ETS2 TELEMETRY MPH"

**Comment by yodek** [comment]
If you want [text / number] speed in mph, in dashboard.js [file in skin folder] you have this line: data.truckSpeedMph = data.truckSpeed * 0.621371;

So, only have to change from truckSpeedRounded to truckSpeedMph in in dashboard.html AND dashboard.css

**Comment by imaggot** [comment]
Ohh cheers i might give that a try :), is it possible to have both kph and mph displayed in two boxes somehow?? Think thatd be cool to have aswell

**Comment by Funbit** [comment]
Thank you for the contribution.
I have released a new MPH version of the default skin in the 2.2.5:
http://forum.scssoft.com/viewtopic.php?f=41&t=171000&p=352992#p352992

**Comment by ta4chu** [comment]
Hi; How can I use this Skin ? Thankyou...

**Comment by Funbit** [comment]
You may download the alternate MPH skin here:
https://www.dropbox.com/s/csdwgk8ul12uaiy/default-mph-alt.zip?dl=0

**Comment by ta4chu** [comment]
Thankyou very much.. Working great...
