### ISSUE TITLE
Incorrect speed and damage values

### ISSUE THREAD

**Issue by maysaraahmad** [Funbit/ets2-telemetry-server#41]
http://i.imgur.com/Frw15tg.png
http://i.imgur.com/jHhDHM4.png

As you can see, the speed showing at the dashboard app isn't exactly as the speed in the game. Also the damage value is way wrong.

**Comment by Phil0499** [comment]
the damage value is not wrong, it is because in the game they only show your highest damage but in the telemetry dashboard it's the total of all damage (cabin + chassis + wheels + transmission). It is just a different way to show you your truck damage.

**Comment by maysaraahmad** [comment]
Well, we need things unified, so one of them will have to show what the other one is showing.

I forgot to mention something about the speed values. Sometimes the telemetry dashboard shows a higher value and sometimes a less value than the actual speed. That costed me a few speed fines to realize.

**Comment by Funbit** [comment]
Phil is right.
As for the speed:
1) the speed meter reflects EXACT speed using floating point values
2) the digital indicator mathematically rounds speed (i.e. 50.9 will be 51). 
So, either the game itself shows wrong speed, rounding it by dropping the floating point part (this may occur only in PAUSE mode too), or data on your screenshot is a bit late.

**Comment by Funbit** [comment]
> Well, we need things unified, so one of them will have to show what the other one is showing.
Well, this is contentions question, actually. The issue you are talking about here is related to the SKIN, not the telemetry server. The current default skin just reflects my thoughts of the vital stuff the driver should see. If you want to create a skin that displays more technical data to the driver - please create one ;) I will be happy to include it in the bundle as an alternate default skin :)

**Comment by Funbit** [comment]
I have replaced Math.round with Math.floor to fix speed difference (it was a surprise that game used floor to round the value incorrectly...).
As for the damage value - I will leave it as is for now. Maybe I will add more detailed damage indicators in the new skins later.
