### ISSUE TITLE
Dashboard is a giant "link" back to skin selection page

### ISSUE THREAD

**Issue by mkoch227** [Funbit/ets2-telemetry-server#42]
I noticed that each skin itself contains what is essentially a giant link back to the skin selection page, regardless of where you tap/click.  This makes it nearly impossible to create a dashboard with multiple tabs (such as the in-game route advisor), as tapping/clicking on a tab will send the user back to the skin selection page. Is there a way to disable this functionality on a skin-by-skin basis?

**Comment by Funbit** [comment]
Thanks for the suggestion. I've moved back event setup to dashboard.js to allow custom click handlers for custom skins.

Fixed in the next version.
