### ISSUE TITLE
hi, I have Idea

### ISSUE THREAD

**Issue by Iwhite67** [Funbit/ets2-telemetry-server#48]
Hello, my name is Alexis and I am a coder on this site: www.white-gaming.fr

Unfortunately, I have the idea to make a program which has a dialogue with the base SQL for the sending of CMR automatically via the software and the telemetry. 
I tried to code the beginning of program except that I have little knows each other C and C. 
For that that I would like to collaborate with you to create a whole system of business administration, Via Web and via Program. 

If you be interested or that you have questions, I am available on this address: iwhite@white-gaming.fr or via Contact on Website.

thank you and soon has

**Comment by Funbit** [comment]
Hi @Iwhite67 ,
I'm sorry, but due to the lack of spare time I can't participate in your project. 

Also, since I don't speak French, I understood only half of your idea. You want to gather ETS2 job information and publish it on your site as a CMR? Could you please describe your idea in detail? Thanks

**Comment by Iwhite67** [comment]
Hi, In fact, it is the software which is going to get back information on the games (the odometre essentially) to complete the present form on the software. Afterward the driver will send him to the server via a button. Hopefully it is better
Thanks, bye

Date: Wed, 25 Mar 2015 18:08:17 -0700

**Comment by thorerik** [comment]
@Iwhite67 I'd guess it's outside the scope of this project to cater to your needs.

Your best options are probably 1. hire someone, 2. find someone who knows C# and have time, or 3. learn C# yourself.

**Comment by Iwhite67** [comment]
OK thank you anyway

Date: Fri, 27 Mar 2015 22:05:08 -0700
