### ISSUE TITLE
New Scania Dashboard

### ISSUE THREAD

**Issue by wajo666** [Funbit/ets2-telemetry-server#49]
Hi,
I found new dashboard for scania http://newsroom.scania.com/en-group/files/2013/02/09596-006.jpg 
https://www.flickr.com/photos/scania/2868265463/in/photostream/ and more pictures.
More information we can use from data. Can you help me with create new dashboard?

**Comment by yodek** [comment]
What kind of help do you need from Funbit ?
You have Default and some others skins [DAF, MAN, Mercedes, Scania, Volvo] - all have enough informations to make your own great skin.

I customized default-skin for my preferences by learning / analyzing code what was used in others skins. For me is a great way to learn JS and other languages used to make websites.

**Comment by Funbit** [comment]
Hi @wajo666 ,
have you read the main page? It contains a skin tutorial, describing all necessary stuff:
https://github.com/Funbit/ets2-telemetry-server#dashboard-skin-tutorial
The only thing you need to have is some HTML/CSS/JS experience, but even basic is enough. 

2 @yodek :
If you want to work on a new skin (or share with others) just create a new git branch and commit your version there. When it is completed I can include your skin into official distribution as well.

**Comment by Funbit** [comment]
I'm closing the issue due to inactivity.

**Comment by mikeltalega** [comment]
hello I would like to know where I can download it and I have become loko to find it and there is no way you can leave link to it
