### ISSUE TITLE
I have a suggestion 

### ISSUE THREAD

**Issue by XeaVex** [Funbit/ets2-telemetry-server#51]
Hi, i love what you made i use it every time i play ets2 but i wanna get rid of the satnav and use the trucks satnav but when i use the trucks i cant see the speed limit marker thing so i was wondering if its possible to add a a speed limit indicator thing on the dashboard that would make the experience a lot better!  :)  
                                                                            P.S. Sorry if i should of put this somewhere else lol

**Comment by yodek** [comment]
At this moment there is no value of 'speed-limit' from SDK Telemetry [data from game].

**Comment by Funbit** [comment]
@XeaVex 
Thank you for the suggestion, but as yodek already said, it is not yet supported by the telemetry SDK.

**Comment by Funbit** [comment]
Implemented in the 3.0.0, please try the latest version!
