### ISSUE TITLE
lightsAux value

### ISSUE THREAD

**Issue by JackWalker** [Funbit/ets2-telemetry-server#54]
lightsAuxFrontOn and lightsAuxRoofOn values are always "false" (ets ver 1.17.1s, telemetry ver 2.2.6)

**Comment by yodek** [comment]
They were always "false" [before Telemetry v2.2.6] and I think the problems is from game, not plugin or server.

**Comment by JackWalker** [comment]
Now with the ver.3.0.0 ver works fine
