### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by Vtelrunya** [Funbit/ets2-telemetry-server#55]
Getting an error when trying to run ETS2Telemetry:
Error message is:
The application was uanble to start correctly (0xc000007b). Click OK to close the application.
I am running Win 7 64 bit system.

![ets2tm_error](https://cloud.githubusercontent.com/assets/12414826/7600345/90e064ea-f90a-11e4-9f55-95b62e1bec9e.png)

**Comment by Funbit** [comment]
Looks like you don't have .NET Framework 4.5 installed. 
Please make sure that you have it installed before running the server:
http://www.microsoft.com/en-us/download/details.aspx?id=30653

If error still presents then there's something wrong with the environment, most probably related to the 3rd party anti-virus/firewall software.

**Comment by Funbit** [comment]
Hello.
Have you managed to solve the issue?
