### ISSUE TITLE
Compileing source code

### ISSUE THREAD

**Issue by SamTDS** [Funbit/ets2-telemetry-server#56]
Because I am using windows XP the pre compiled .exe doesn't work for me and I was wondering how to compile the source code myself. I have been searching on Google to find out how and have no luck. I'm thinking Microsoft visual studio will work but I unfortunately don't have the disk space to get it :(.

**Comment by Funbit** [comment]
Hello Sam,

unfortunately Windows XP is not supported. 
Please take a look at the existing topic about that:

https://github.com/Funbit/ets2-telemetry-server/issues/26
