### ISSUE TITLE
It adds that the server sends the page publicly as an option

### ISSUE THREAD

**Issue by jeremy100** [Funbit/ets2-telemetry-server#69]
It would be nice to convey our panel to friends, but I do not know if you can currently do. If so can you tell me that I have to edit or do to convey my panel truck?

**Comment by Funbit** [comment]
It is already possible, just select proper network interface in the main server window and setup your router for other people to connect to your PC via your public IP (so your friends will be able to open your telemetry page by opening http://yourpublicip:25555/). There are plenty tutorials out there, like this: http://www.howtogeek.com/66214/how-to-forward-ports-on-your-router/
Hope it will help.

**Comment by jeremy100** [comment]
Thanks Funbit, the problem was my Firewall. But I knew open ports on the router. a greeting
