### ISSUE TITLE
request - job completed (in latest sdk)

### ISSUE THREAD

**Issue by dualznz** [Funbit/ets2-telemetry-server#70]
hi i would like to request job completed check, it was added in the latest version of the sdk, isjobcompleted i think cheers

**Comment by Funbit** [comment]
Will look at it, thanks

**Comment by Megachip** [comment]
@dualznz Where did you see it? Can't find anything belongs to job completion in SDK 1.5.

But should not be to complicated to implement? Simply monitor some job and trailer values for changes!?

**Comment by Funbit** [comment]
Please follow this discussion:
https://github.com/Funbit/ets2-telemetry-server/issues/76#issuecomment-186745073
