### ISSUE TITLE
American Truck Simulator Support

### ISSUE THREAD

**Issue by mike-koch** [Funbit/ets2-telemetry-server#73]
ATS was released earlier today, and I did some testing to see how much work would need to be done to make the telemetry server work on ATS. Here's what I have figured out so far:

- The .dll that is installed for ETS2 seems to work with ATS (so nothing needs to be changed with the dll)
- Update `Ets2ProcessHelper` to check if either ETS2 or ATS is running (process is `amtrucks.exe` with title `American Truck Simulator`)
- I suppose the installer should also be updated to copy the dll to the ATS folder as well (if it exists)

Also, is it worth changing the name of the telemetry server? I personally have no preference.

**PR #74 addresses this issue**

**Comment by mike-koch** [comment]
Please explain what doesn't work. Did you download build 3.1.0?

**Comment by justinross7j** [comment]
i need help with it working in ats. my server says ats is running. and my tablet says connected. but it doesnt show any info on the tablet. no mph or rpm or anything. any help? thanks

**Comment by Teichinator** [comment]
Can you explain what to do to use Telemetry in ATS?
Please do it step by step.

**Comment by justinross7j** [comment]
I finally got it to work. Thanks

**Comment by nak0604** [comment]
Where can I download 3.1.0?

**Comment by mike-koch** [comment]
The unofficial build can be downloaded at https://github.com/mike-koch/ets2-telemetry-server/releases/tag/3.1.0

**Comment by Funbit** [comment]
Thank you very much Mike, I have released new server with ATS support (3.2.0). I didn't use your pull request, but have merged almost everything you did (except the new setup, I decided to left it the way it was, have some thoughts about additional improvements though).

**Comment by trooper2k** [comment]
I'm still having problems  with ats

**Comment by mike-koch** [comment]
@trooper2k explain what isn't working with ATS. Just saying "I'm having problems" doesn't allow us to help in any way.

**Comment by trooper2k** [comment]
# ets works but the map don't

**Comment by trooper2k** [comment]
The dash bore on ats not working  sorry

**Comment by trooper2k** [comment]
I did step by step  there's got to be something I'm missing

**Comment by mike-koch** [comment]
Which skin are you using? Only one skin (mike-koch/ets2-mobile-route-advisor) has a map for ATS (which currently is out-of-date and will be for some time; see https://github.com/mike-koch/ets2-mobile-route-advisor/issues/128)

**Comment by trooper2k** [comment]
OK so ats is out dated 👌 that's fine
