### ISSUE TITLE
URL Path Limit?

### ISSUE THREAD

**Issue by mike-koch** [Funbit/ets2-telemetry-server#79]
I'm trying to add support for various "map packs" in my skin, and I've noticed that after a specific number of folders, everything starts returning a 404.  For example, I am able to view the following JPG in my browser at the following path:

```
http://localhost:25555/skins/ets2-mobile-route-advisor/maps/ets2/tiles/dashboard.jpg
```

This link returns a 200 status code with the image displayed in the browser.

However, if I create a new folder (let's call it `0`), and place my image into this new folder, the URL **should** become:

```
http://localhost:25555/skins/ets2-mobile-route-advisor/map/ets2/tiles/0/dashboard.jpg
```

However, this link will return a **404** with no image being displayed.  Is there some sort of "magic number" that limits the length of the URL, and I somehow reached this limit?

**Comment by Funbit** [comment]
Yes, there is.. Sorry about that, I did not think that skin development would go so far :) 
The fix is pretty easy, so I will release the update today.

**Comment by mike-koch** [comment]
Haha no worries. I was just confused for a moment when things suddenly stopped working :laughing:

**Comment by Funbit** [comment]
Fixed in the latest update, please let me know if I can close the issue.

**Comment by mike-koch** [comment]
The changes work for me :smile: (only using 7 of the 9 subdirectory levels lol).

**Comment by Funbit** [comment]
Good to hear :)
