### ISSUE TITLE
SVG images do not work

### ISSUE THREAD

**Issue by Koenvh1** [Funbit/ets2-telemetry-server#80]
Like the title says above, SVG images are currently not supported. Support for SVG images would be ideal for scaling and size.

**Comment by mike-koch** [comment]
@Koenvh1 SVG images are used throughout `ets2-mobile-route-advisor` (all of the icons are driven by SVG images).  The issue may be specific with OpenLayers, not `ets2-telemetry-server`

**Comment by Koenvh1** [comment]
@mike-koch That is not the case, because http://denilson.sa.nom.br/ets2-stuff/openlayers-koenvh1.html also uses SVG images. Using ETS2 Telemetry Server, it shows a download prompt instead of displaying it, which makes me think it doesn't work... I could be wrong too.

**Comment by yodek** [comment]
Isn't problem with browser (settings)? I use FF and Chrome - none of them never ask me to download SVG...
Can you give a link to website? Or (if it skin for Funbit's Telemetry) upload to Github so I could download and check in my place.
In the website you gave link  - ETS2-Stuff-OpelLayers - I see... PNG file.

**Comment by Koenvh1** [comment]
It's the skin, because other websites (Wikipedia etc) do not ask me to download it.
And you're seeing a PNG file indeed, but the flag icons are SVGs. They work there, but not in ETS2 Telemetry Server. See [this](https://github.com/mike-koch/ets2-mobile-route-advisor) link, and change in the [maps/ets2/map.js file](https://github.com/mike-koch/ets2-mobile-route-advisor/blob/master/maps/ets2/js/map.js) line 115 from `src: g_pathPrefix + '/flags_png/' + this.get('cc') + '.png',` to `src: g_pathPrefix + '/flags/' + this.get('cc') + '.svg',`
You'll see that the city names are gone now.

**Comment by Funbit** [comment]
Sorry for the late reply.
I havent tested it yet, but I believe that the server does not support SVG files indeed. I will add SVG content type support today, stay tuned.

**Comment by Funbit** [comment]
Fixed in the latest 3.2.4 version.
