### ISSUE TITLE
Connected, waiting for the drive... simulator not running issue!

### ISSUE THREAD

**Issue by VioletSnow08** [Funbit/ets2-telemetry-server#83]
Please help I am running the server on my mac using wine

**Comment by mike-koch** [comment]
Are you running ETS2 with wine as well? The ETS2 Telemetry DLL only works on Windows PCs, and I personally have not tried using this DLL with Wine.

**Comment by VioletSnow08** [comment]
No.

**Comment by dualznz** [comment]
As far as um aware wine will not work correctly parallels desktop Mac will as it creates a VM instance of the os but can't 100% confirm

**Comment by VioletSnow08** [comment]
K. I will try parallels. Thanks

**Comment by VioletSnow08** [comment]
Ok I tried parallels but I can't use the trial because I have used them before... Is there another way I can do it?

**Comment by dualznz** [comment]
Unfortunately no not unless you buy the software, Mac by default is not supported, so no support for Mac can be given

**Comment by mike-koch** [comment]
You _could_ try using VirtualBox (free), or you can set up a Boot Camp instance and have a dual-boot between Windows and OS X.

**Comment by VioletSnow08** [comment]
K. Thank you for all the help!
