### ISSUE TITLE
I created a overwolf app as client :)

### ISSUE THREAD

**Issue by Bluscream** [Funbit/ets2-telemetry-server#90]
https://github.com/Bluscream/Route-Advisor-Overwolf-App
http://www.overwolf.com/
https://www.youtube.com/watch?v=9zJWt3rfhpg

**Comment by Funbit** [comment]
I think you should add simple usage instructions to the readme, it's not clear how to use the app, even for me :)

**Comment by Bluscream** [comment]
https://www.youtube.com/watch?v=9zJWt3rfhpg

**Comment by Bluscream** [comment]
I hope you understand it now, i added a link to the official Homepage and that quick YouTube video :)

**Comment by Funbit** [comment]
Yea, now I see! Nice :)
