### ISSUE TITLE
Connected, waiting for the drive

### ISSUE THREAD

**Issue by haydayhacktool** [Funbit/ets2-telemetry-server#98]
Hello,

I have downloaded the ets2 telemetry server but I can`t make it work. I start the server and the game and everything looks fine, the server says connected to the simulator. But when I go to the URL of the server and select a skin it says: "connected, waiting for the drive" when I click "drive" and I'm driving in the game. I have Bitdefender antivirus and I have opened the firewall port, can this affect? I have checked everything and browsed for a solution but I couldn't find one. 
Does someone else have this problem? Does someone know how to fix it?

Thanks

**Comment by mike-koch** [comment]
Typically that message appears when the game is running and your device is connected to the server, but you haven't clicked "drive" in-game for the first time.  Does the message continue to appear once you have already started driving?

**Comment by haydayhacktool** [comment]
Yes, that message doesn't change when I click Drive or later when I am driving.

**Comment by haydayhacktool** [comment]
I have updated ets2 and now the server is working.

Thanks

**Comment by haydayhacktool** [comment]
I
